# netlify.toml

# This section defines the build settings for your site.
[build]
  # This command tells Netlify to install dependencies and then run your build script.
  # It runs from the root of your repository, where your package.json is located.
  command = "npm install && npm run build"
  
  # This tells Netlify that the finished HTML files are in the root of the repository.
  publish = "public"

# This section specifies the Node.js version to use.
[build.environment]
  NODE_VERSION = "16"

  [functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
# Redirect for the support subdomain
[[redirects]]
  from = "https://support.caprocktech.com/"
  to = "https://caprocktech.servicedesk.atera.com/"
  status = 301
  force = true

# Redirect for the /support path
[[redirects]]
  from = "/support"
  to = "https://caprocktech.rmmservices.net/"
  status = 301
  force = true
