# netlify.toml

# This section defines the build settings for your site.
[build]
  # Base directory: Tells Netlify to change into this folder before running the build command.
  base = "caprock-site-files"
  
  # This is the command Netlify will run to build your site.
  command = "npm run build"
  
  # Publish directory: The folder that contains the final HTML files after the build is complete.
  publish = "caprock-site-files"

# This section specifies the Node.js version to use.
# This setting has the highest priority and will override any other configurations.
[build.environment]
  NODE_VERSION = "16"
