import Link from 'next/link';
import MobileNav from './mobile-nav';
import { Download,GraduationCap,Calendar,Check,Camera } from 'lucide-react';
import type { Product,Store } from '@/lib/types';
import { money,typeLabel } from '@/lib/types';
export function Logo(){return <Link href="/" className="logo" aria-label="Folio home"><span className="logo-mark">f</span>folio</Link>}
export function Nav({purple=false}:{purple?:boolean}){return <header style={purple?{color:'white'}:{borderBottom:'1px solid #efedf5'}}><div className="container nav"><Logo/><nav className="navlinks" aria-label="Main navigation"><Link href="/#features">Features</Link><Link href="/about">Our mission</Link><Link href="/learn">Resources</Link><Link href="/compare">Compare</Link></nav><div className="nav-actions"><MobileNav/><Link className="login-link" href="/login">Log in</Link><Link href="/signup" className={`btn ${purple?'white':''}`}>Create your store</Link></div></div></header>}
export function Footer(){return <footer className="footer container"><div className="footer-top"><div><Logo/><p>A little link. A world of possibilities.</p></div><nav className="footer-links" aria-label="Footer"><Link href="/about">Our mission</Link><Link href="/pricing">Pricing</Link><Link href="/compare">Comparisons</Link><Link href="/learn">Resources</Link><Link href="/help">Help</Link><Link href="/login">Log in</Link></nav></div><div className="footer-bottom"><span>© 2026 Folio. Made for your next chapter.</span><span>Independent product. Not affiliated with Stan or the platforms compared.</span></div></footer>}
export function Avatar({store,className=''}:{store:Pick<Store,'name'|'avatar'>;className?:string}){return store.avatar?<img src={store.avatar} alt={store.name} className={'avatar '+className}/>:<span className={'avatar initials '+className}>{store.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>}
export function ProductIcon({type,size=28}:{type:string;size?:number}){const Icon=type==='course'?GraduationCap:type==='booking'?Calendar:Download;return <Icon size={size} strokeWidth={1.7}/>}
export function ProductArt({product}:{product:Pick<Product,'cover'|'type'|'title'>}){return <div className={'product-art '+product.type}>{product.cover?<img src={product.cover} alt={product.title}/>:<ProductIcon type={product.type}/>}</div>}
export function MiniProduct({product,handle}:{product:Product;handle:string}){return <Link href={`/s/${handle}/p/${product.id}`} className="mini-card"><div className="row"><div className="icon-tile"><ProductIcon type={product.type} size={22}/></div><div><h3>{product.title}</h3><p>{money(product.price)} · {typeLabel[product.type]}</p></div></div><span className="mini-cta">{product.type==='booking'?'Book a session':product.type==='course'?'Explore the course':'Get the download'}</span></Link>}
export function CTA(){return <div className="cta-band"><h2>Your next chapter starts here.</h2><Link className="btn mint pill" href="/signup">Create your store</Link><p>No card required. Start with a free product.</p></div>}
export const SampleStore={name:'Maya Chen',avatar:'/creator.webp'};
export const sampleProducts:Product[]=[{id:'sample-planner',store_id:'public-maya-store',title:'The Content Planner',description:'Your next 30 days of content, sorted.',type:'download',price:0,cover:'',duration:30,published:1,position:0},{id:'sample-course',store_id:'public-maya-store',title:'From Idea to Your First Offer',description:'Three practical lessons to get you started.',type:'course',price:4900,cover:'',duration:30,published:1,position:1},{id:'sample-call',store_id:'public-maya-store',title:'Let’s Talk About Your Next Move',description:'A focused 30-minute conversation.',type:'booking',price:7500,cover:'',duration:30,published:1,position:2}];
